### ISSUE TITLE
Errors while compiling

### ISSUE THREAD

**Issue by pavel-milosh** [fiqri19102002/android_kernel_xiaomi_sweet#1]
How can i fix it? I use clang-16 and gcc
`aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `__read_once_size':
/root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x33c): undefined reference to `__tracepoint_bus_update_request'
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_update_request' which may bind externally can not be used when making a shared object; recompile with -fPIC
/root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x33c): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x340): undefined reference to `__tracepoint_bus_update_request'
aarch64-linux-gnu-ld: /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x390): undefined reference to `__tracepoint_bus_update_request'
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_update_request' which may bind externally can not be used when making a shared object; recompile with -fPIC
/root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x390): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x394): undefined reference to `__tracepoint_bus_update_request'
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `msm_bus_dbg_fill_cl_buffer':
/root/android_kernel_xiaomi_sweet/out/../drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.c:556:(.text+0x9f8): undefined reference to `__tracepoint_bus_update_request'
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_update_request' which may bind externally can not be used when making a shared object; recompile with -fPIC
/root/android_kernel_xiaomi_sweet/out/../drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.c:556:(.text+0x9f8): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o:/root/android_kernel_xiaomi_sweet/out/../include/linux/rcupdate.h:775: more undefined references to `__tracepoint_bus_update_request' follow
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_update_request' which may bind externally can not be used when making a shared object; recompile with -fPIC
drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `msm_bus_dbg_fill_cl_buffer':
/root/android_kernel_xiaomi_sweet/out/../include/linux/rcupdate.h:775:(.text+0xa14): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_update_request' which may bind externally can not be used when making a shared object; recompile with -fPIC
drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `__read_once_size':
/root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0xa94): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_update_request' which may bind externally can not be used when making a shared object; recompile with -fPIC
drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `__write_once_size':
/root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:211:(.text+0xae8): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `msm_bus_dbg_dump_clients_read':
/root/android_kernel_xiaomi_sweet/out/../drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.c:886:(.text+0x15a8): undefined reference to `__tracepoint_bus_client_status'
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_client_status' which may bind externally can not be used when making a shared object; recompile with -fPIC
/root/android_kernel_xiaomi_sweet/out/../drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.c:886:(.text+0x15a8): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `msm_bus_dbg_dump_clients_read':
/root/android_kernel_xiaomi_sweet/out/../include/linux/rcupdate.h:775:(.text+0x1600): undefined reference to `__tracepoint_bus_client_status'
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_client_status' which may bind externally can not be used when making a shared object; recompile with -fPIC
/root/android_kernel_xiaomi_sweet/out/../include/linux/rcupdate.h:775:(.text+0x1600): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `__read_once_size':
/root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x1644): undefined reference to `__tracepoint_bus_client_status'
aarch64-linux-gnu-ld: /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x168c): undefined reference to `__tracepoint_bus_client_status'
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_client_status' which may bind externally can not be used when making a shared object; recompile with -fPIC
/root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x168c): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x1690): undefined reference to `__tracepoint_bus_client_status'
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o:/root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:211: more undefined references to `__tracepoint_bus_client_status' follow
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_client_status' which may bind externally can not be used when making a shared object; recompile with -fPIC
drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `__write_once_size':
/root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:211:(.text+0x16d8): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `bcm_client_read':
/root/android_kernel_xiaomi_sweet/out/../drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.c:813:(.text+0x17e0): undefined reference to `__tracepoint_bus_bcm_client_status'
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_bcm_client_status' which may bind externally can not be used when making a shared object; recompile with -fPIC
/root/android_kernel_xiaomi_sweet/out/../drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.c:813:(.text+0x17e0): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `__read_once_size':
/root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x1970): undefined reference to `__tracepoint_bus_bcm_client_status'
aarch64-linux-gnu-ld: /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x19bc): undefined reference to `__tracepoint_bus_bcm_client_status'
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_bcm_client_status' which may bind externally can not be used when making a shared object; recompile with -fPIC
/root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x19bc): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x19c0): undefined reference to `__tracepoint_bus_bcm_client_status'
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `__write_once_size':
/root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:211:(.text+0x1a04): undefined reference to `__tracepoint_bus_bcm_client_status'
aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_bcm_client_status' which may bind externally can not be used when making a shared object; recompile with -fPIC
/root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:211:(.text+0x1a04): dangerous relocation: unsupported relocation
aarch64-linux-gnu-ld: drivers/net/wireless/ath/wil6210/wil_platform.o: in function `wil_platform_modexit':
/root/android_kernel_xiaomi_sweet/out/../drivers/net/wireless/ath/wil6210/wil_platform.c:28:(.text+0x8): undefined reference to `msm_11ad_modexit'
aarch64-linux-gnu-ld: drivers/net/wireless/ath/wil6210/wil_platform.o: in function `wil_platform_init':
/root/android_kernel_xiaomi_sweet/out/../drivers/net/wireless/ath/wil6210/wil_platform.c:49:(.text+0x2c): undefined reference to `msm_11ad_dev_init'
aarch64-linux-gnu-ld: drivers/net/wireless/ath/wil6210/wil_platform.o: in function `wil_platform_modinit':
/root/android_kernel_xiaomi_sweet/out/../drivers/net/wireless/ath/wil6210/wil_platform.c:23:(.init.text+0x8): undefined reference to `msm_11ad_modinit'`

**Comment by fiqri19102002** [comment]
> How can i fix it? I use clang-16 and gcc `aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `__read_once_size': /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x33c): undefined reference to `__tracepoint_bus_update_request' aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_update_request' which may bind externally can not be used when making a shared object; recompile with -fPIC /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x33c): dangerous relocation: unsupported relocation aarch64-linux-gnu-ld: /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x340): undefined reference to `__tracepoint_bus_update_request' aarch64-linux-gnu-ld: /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x390): undefined reference to `__tracepoint_bus_update_request' aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_update_request' which may bind externally can not be used when making a shared object; recompile with -fPIC /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x390): dangerous relocation: unsupported relocation aarch64-linux-gnu-ld: /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x394): undefined reference to `__tracepoint_bus_update_request' aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `msm_bus_dbg_fill_cl_buffer': /root/android_kernel_xiaomi_sweet/out/../drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.c:556:(.text+0x9f8): undefined reference to `__tracepoint_bus_update_request' aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_update_request' which may bind externally can not be used when making a shared object; recompile with -fPIC /root/android_kernel_xiaomi_sweet/out/../drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.c:556:(.text+0x9f8): dangerous relocation: unsupported relocation aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o:/root/android_kernel_xiaomi_sweet/out/../include/linux/rcupdate.h:775: more undefined references to `__tracepoint_bus_update_request' follow aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_update_request' which may bind externally can not be used when making a shared object; recompile with -fPIC drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `msm_bus_dbg_fill_cl_buffer': /root/android_kernel_xiaomi_sweet/out/../include/linux/rcupdate.h:775:(.text+0xa14): dangerous relocation: unsupported relocation aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_update_request' which may bind externally can not be used when making a shared object; recompile with -fPIC drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `__read_once_size': /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0xa94): dangerous relocation: unsupported relocation aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_update_request' which may bind externally can not be used when making a shared object; recompile with -fPIC drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `__write_once_size': /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:211:(.text+0xae8): dangerous relocation: unsupported relocation aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `msm_bus_dbg_dump_clients_read': /root/android_kernel_xiaomi_sweet/out/../drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.c:886:(.text+0x15a8): undefined reference to `__tracepoint_bus_client_status' aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_client_status' which may bind externally can not be used when making a shared object; recompile with -fPIC /root/android_kernel_xiaomi_sweet/out/../drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.c:886:(.text+0x15a8): dangerous relocation: unsupported relocation aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `msm_bus_dbg_dump_clients_read': /root/android_kernel_xiaomi_sweet/out/../include/linux/rcupdate.h:775:(.text+0x1600): undefined reference to `__tracepoint_bus_client_status' aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_client_status' which may bind externally can not be used when making a shared object; recompile with -fPIC /root/android_kernel_xiaomi_sweet/out/../include/linux/rcupdate.h:775:(.text+0x1600): dangerous relocation: unsupported relocation aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `__read_once_size': /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x1644): undefined reference to `__tracepoint_bus_client_status' aarch64-linux-gnu-ld: /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x168c): undefined reference to `__tracepoint_bus_client_status' aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_client_status' which may bind externally can not be used when making a shared object; recompile with -fPIC /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x168c): dangerous relocation: unsupported relocation aarch64-linux-gnu-ld: /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x1690): undefined reference to `__tracepoint_bus_client_status' aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o:/root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:211: more undefined references to `__tracepoint_bus_client_status' follow aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_client_status' which may bind externally can not be used when making a shared object; recompile with -fPIC drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `__write_once_size': /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:211:(.text+0x16d8): dangerous relocation: unsupported relocation aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `bcm_client_read': /root/android_kernel_xiaomi_sweet/out/../drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.c:813:(.text+0x17e0): undefined reference to `__tracepoint_bus_bcm_client_status' aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_bcm_client_status' which may bind externally can not be used when making a shared object; recompile with -fPIC /root/android_kernel_xiaomi_sweet/out/../drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.c:813:(.text+0x17e0): dangerous relocation: unsupported relocation aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `__read_once_size': /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x1970): undefined reference to `__tracepoint_bus_bcm_client_status' aarch64-linux-gnu-ld: /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x19bc): undefined reference to `__tracepoint_bus_bcm_client_status' aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_bcm_client_status' which may bind externally can not be used when making a shared object; recompile with -fPIC /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x19bc): dangerous relocation: unsupported relocation aarch64-linux-gnu-ld: /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:185:(.text+0x19c0): undefined reference to `__tracepoint_bus_bcm_client_status' aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: in function `__write_once_size': /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:211:(.text+0x1a04): undefined reference to `__tracepoint_bus_bcm_client_status' aarch64-linux-gnu-ld: drivers/soc/qcom/msm_bus/msm_bus_dbg_rpmh.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__tracepoint_bus_bcm_client_status' which may bind externally can not be used when making a shared object; recompile with -fPIC /root/android_kernel_xiaomi_sweet/out/../include/linux/compiler.h:211:(.text+0x1a04): dangerous relocation: unsupported relocation aarch64-linux-gnu-ld: drivers/net/wireless/ath/wil6210/wil_platform.o: in function `wil_platform_modexit': /root/android_kernel_xiaomi_sweet/out/../drivers/net/wireless/ath/wil6210/wil_platform.c:28:(.text+0x8): undefined reference to `msm_11ad_modexit' aarch64-linux-gnu-ld: drivers/net/wireless/ath/wil6210/wil_platform.o: in function `wil_platform_init': /root/android_kernel_xiaomi_sweet/out/../drivers/net/wireless/ath/wil6210/wil_platform.c:49:(.text+0x2c): undefined reference to `msm_11ad_dev_init' aarch64-linux-gnu-ld: drivers/net/wireless/ath/wil6210/wil_platform.o: in function `wil_platform_modinit': /root/android_kernel_xiaomi_sweet/out/../drivers/net/wireless/ath/wil6210/wil_platform.c:23:(.init.text+0x8): undefined reference to `msm_11ad_modinit'`

Did you make any changes to sweet defconfig?

**Comment by pavel-milosh** [comment]
No, I did not. But I made some changes in code, because I had errors while compiling

**Comment by pavel-milosh** [comment]
Should I use sweet_defconfig or sweet-stock_defconfig?

**Comment by fiqri19102002** [comment]
> Should I use sweet_defconfig or sweet-stock_defconfig?

sweet_defconfig and use build.sh script
